name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:

    name: build
    runs-on: macos-ventura

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
        fetch-depth: 0
        lfs: true

    - name: Build, test, and release
      env:
        DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64: ${{ secrets.DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64 }}
        DEVELOPER_ID_APPLICATION_CERTIFICATE_PASSWORD: ${{ secrets.DEVELOPER_ID_APPLICATION_CERTIFICATE_PASSWORD }}
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE: ${{ github.ref == 'refs/heads/main' }}
      run: |
        Scripts/bootstrap.sh Scripts/build.sh

    - name: Archive the build directory
      uses: actions/upload-artifact@v3
      with:
        path: build
        if-no-files-found: error

    - name: Archive the command
      uses: actions/upload-artifact@v3
      with:
        path: build/incontext-*.zip
        if-no-files-found: error

  update-homebrew:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:

    - name: Update Homebrew formula
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets._GITHUB_ACCESS_TOKEN }}
        repository: inseven/homebrew-incontext
        event-type: update
