name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  test:

    name: build
    runs-on: macos-ventura

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
        lfs: true

    - name: Build and test
      run: |
        swift build
        swift test
